version: '3'
services:
  microservicos-back:
    image: afileni/microservicos-redis
    container_name: microservicos-redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  microservicos-front:
    image: afileni/microservicos-app
    container_name: microservicos-app
    environment:
      REDIS: microservicos-redis
    ports:
        - "8080:80"
