version: '3'
services:
  microservicos-back:
    image: afileni/microservicos-redis
    container_name: microservicos-redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  microservicos-front:
    build: ./app
#    image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
    container_name: microservicos-front
    environment:
      REDIS: microservicos-redis
    ports:
        - "8080:80"
