version: '3'
services:
  microservicos-redis:
    image: afileni/microservicos-redis
    container_name: microservicos-redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  microservicos-app:
    image: afileni/microservicos-app
    container_name: microservicos-app
    environment:
      REDIS: microservicos-redis
    ports:
        - "8080:80"
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
        condition: on-failure
